### ISSUE TITLE
code=46(cudaErrorDevicesUnavailable) - Can't allocate [DEVICE] reduction buffer memory!

### ISSUE THREAD

**Issue by GitLack** [deeplearning4j/libnd4j#217]
------------------
System Information
------------------
Operating System: Windows 10 Pro 64-bit (10.0, Build 10586) (10586.th2_release_sec.160422-1850)
Processor: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 CPUs), ~2.6GHz
Memory: 16384MB RAM
Intel(R) HD Graphics 4600
NVIDIA GeForce GTX 980M

I ran any of the examples in [https://github.com/deeplearning4j/dl4j-0.4-examples](url) and I got this error. I also had to add the javacpp dependency.

I have cuda 7.5, reinstalled and nvidia drivers up to date. 

```
o.n.j.c.CudaEnvironment - Please note, CudaEnvironment is already initialized. Configuration changes won't have effect
o.d.n.c.NeuralNetConfiguration - Layer not named l1 or l2 has been added to configuration but useRegularization is set to false.
o.d.n.c.NeuralNetConfiguration - Layer not named l1 or l2 has been added to configuration but useRegularization is set to false.
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Can't allocate [DEVICE] reduction buffer memory!
	at org.nd4j.jita.allocator.context.impl.BasicContextPool.acquireContextForDevice(BasicContextPool.java:135)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.getCudaContext(CudaZeroHandler.java:1083)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:194)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:374)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:336)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:142)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:44)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:226)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1161)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:225)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:249)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:526)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:239)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:221)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4030)
	at org.nd4j.linalg.api.rng.DefaultRandom.nextGaussian(DefaultRandom.java:121)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.randn(BaseNDArrayFactory.java:707)
	at org.nd4j.linalg.factory.Nd4j.randn(Nd4j.java:2494)
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:113)
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:82)
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:132)
	at org.deeplearning4j.nn.params.DefaultParamInitializer.createWeightMatrix(DefaultParamInitializer.java:74)
	at org.deeplearning4j.nn.params.DefaultParamInitializer.init(DefaultParamInitializer.java:46)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.getParams(DefaultLayerFactory.java:107)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.create(DefaultLayerFactory.java:64)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:361)
	at org.deeplearning4j.examples.feedforward.classification.MLPClassifierLinear.main(MLPClassifierLinear.java:83)
Caused by: java.lang.IllegalStateException: Can't allocate [DEVICE] reduction buffer memory!
	at org.nd4j.jita.allocator.context.impl.BasicContextPool.getDeviceBuffers(BasicContextPool.java:230)
	at org.nd4j.jita.allocator.context.impl.BasicContextPool.acquireContextForDevice(BasicContextPool.java:90)
	... 26 more
CUDA error at C:/projects/skymind_deploy/libnd4j/blas/cuda/NativeOps.cu:4036 code=46(cudaErrorDevicesUnavailable) "result" 
CUDA error at C:/projects/skymind_deploy/libnd4j/blas/cuda/NativeOps.cu:4036 code=46(cudaErrorDevicesUnavailable) "result" 
```

When I tested with the solution at [https://github.com/deeplearning4j/libnd4j/blob/master/windows.md#my-application-crashes-on-the-first-usage-of-nd4j-with-the-cuda-backend-windows](url), I got the same error.

**Comment by raver119** [comment]
Well, in all (literally all) cases, the only thing that helped to people is CUDA Toolkit reinstallation. Not sure why, though. CUDA error 46 reports are totally out of our control. It feels like binary incompatibility, despite static cudart building.

So, just reinstall CUDA Toolkit and you'll be fine. Meanwhile we'll try to get to the roots of this issue.

**Comment by osipov** [comment]
Setting PATH and DYLD_LIBRARY_PATH variables as described in the link below removed the error message. http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-mac-os-x/#axzz4CyT6XHK6

**Comment by raver119** [comment]
Thanks for letting us know!

**Comment by henryfw** [comment]
Somehow, the error went away after I did step 4 of the installation by running http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-mac-os-x/:

make -C 0_Simple/vectorAdd
make -C 0_Simple/vectorAddDrv
make -C 1_Utilities/deviceQuery
make -C 1_Utilities/bandwidthTest 

Also, the instructions uses version 7.0 in the .bash_profile. The current version is 7.5.
